
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IPEBCSCV.BusinessEntity
{

using System;
    using System.Collections.Generic;
    
public partial class Accion
{

    public Accion()
    {

        this.incidencias = new HashSet<Incidencia>();

    }


    public int AccionId { get; set; }

    public string Descripcion { get; set; }



    public virtual ICollection<Incidencia> incidencias { get; set; }

}

}
