

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IPEBCSCV.BusinessEntity
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ipebc_scvEntities : DbContext
{
    public ipebc_scvEntities()
        : base("name=ipebc_scvEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Municipio> municipio { get; set; }

    public DbSet<Regla> regla { get; set; }

    public DbSet<RevisionVehiculo> revision_vehiculo { get; set; }

    public DbSet<Servicio> servicio { get; set; }

    public DbSet<TipoServicio> tipo_servicio { get; set; }

    public DbSet<Usuario> usuario { get; set; }

    public DbSet<Vehiculo> vehiculo { get; set; }

    public DbSet<Rol> rol { get; set; }

    public DbSet<MarcaVehiculo> marca_vehiculo { get; set; }

    public DbSet<Incidencia> incidencias { get; set; }

    public DbSet<Accion> accion { get; set; }

}

}

