//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPEBCSCV.BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regla
    {
        public Regla()
        {
            this.vehiculo = new HashSet<Vehiculo>();
        }
    
        public int ReglaId { get; set; }
        public string Nombre { get; set; }
        public double Kilometraje { get; set; }
        public int Meses { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int TipoServicioId { get; set; }
    
        public virtual TipoServicio tipo_servicio { get; set; }
        public virtual ICollection<Vehiculo> vehiculo { get; set; }
    }
}
