//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPEBCSCV.BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServicio
    {
        public TipoServicio()
        {
            this.regla = new HashSet<Regla>();
            this.servicio = new HashSet<Servicio>();
        }
    
        public int TipoServicioId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual ICollection<Regla> regla { get; set; }
        public virtual ICollection<Servicio> servicio { get; set; }
    }
}
