
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IPEBCSCV.BusinessEntity
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario
{

    public Usuario()
    {

        this.revision_vehiculo = new HashSet<RevisionVehiculo>();

        this.servicio = new HashSet<Servicio>();

        this.incidencias = new HashSet<Incidencia>();

    }


    public int UsuarioId { get; set; }

    public string NombreCompleto { get; set; }

    public string NombreUsuario { get; set; }

    public string Password { get; set; }

    public bool Baja { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public int MunicipioId { get; set; }

    public int RolId { get; set; }



    public virtual ICollection<RevisionVehiculo> revision_vehiculo { get; set; }

    public virtual ICollection<Servicio> servicio { get; set; }

    public virtual Municipio municipio { get; set; }

    public virtual Rol rol { get; set; }

    public virtual ICollection<Incidencia> incidencias { get; set; }

}

}
