
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IPEBCSCV.BusinessEntity
{

using System;
    using System.Collections.Generic;
    
public partial class Vehiculo
{

    public Vehiculo()
    {

        this.revision_vehiculo = new HashSet<RevisionVehiculo>();

        this.servicio = new HashSet<Servicio>();

        this.incidencias = new HashSet<Incidencia>();

    }


    public int VehiculoId { get; set; }

    public string Modelo { get; set; }

    public string Color { get; set; }

    public string Placas { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string Serie { get; set; }

    public int NumeroEconomico { get; set; }

    public string NombrePersona { get; set; }

    public int ReglaId { get; set; }

    public int MunicipioId { get; set; }

    public int MarcaVehiculoId { get; set; }

    public int Kilometraje { get; set; }

    public bool Hide { get; set; }

    public int KilometrajeTotal { get; set; }



    public virtual Municipio municipio { get; set; }

    public virtual Regla regla { get; set; }

    public virtual ICollection<RevisionVehiculo> revision_vehiculo { get; set; }

    public virtual ICollection<Servicio> servicio { get; set; }

    public virtual MarcaVehiculo marca_vehiculo { get; set; }

    public virtual ICollection<Incidencia> incidencias { get; set; }

}

}
